# Generated by Django 3.1.3 on 2021-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201230_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterChoice', models.CharField(choices=[('Name', 'Name ascending'), ('-Name', 'Name descending'), ('Price', 'Price ascending'), ('-Price', 'Price descending'), ('Category', 'Category ascending'), ('-Category', 'Category descending')], default='Name', max_length=25)),
                ('isOnSale', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
            ],
        ),
    ]
