# Generated by Django 3.1.3 on 2022-04-15 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_filterproduct'),
        ('order', '0003_auto_20210107_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='email',
            field=models.EmailField(help_text='E-mail address of a purchaser. An order confirmation is sent to this e-mail address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='firstName',
            field=models.CharField(help_text='First name of a purchaser.', max_length=150),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='lastName',
            field=models.CharField(help_text='Last name of a purchaser.', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryAddress',
            field=models.ForeignKey(help_text='Delivery address of the order.', on_delete=django.db.models.deletion.DO_NOTHING, to='order.deliveryaddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isConfirmed',
            field=models.BooleanField(default=False, help_text='Indicates if the order is confirmed.'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='order',
            field=models.ForeignKey(help_text='Associated order.', on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(help_text='Order element.', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='quantity',
            field=models.IntegerField(help_text='Quantity of elements.'),
        ),
    ]
