# Generated by Django 3.1.3 on 2022-04-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220414_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryAddress',
        ),
        migrations.RemoveField(
            model_name='orderelement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderelement',
            name='product',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderElement',
        ),
    ]
